const CONST = {
  PAGE_MIN: 0x100,
  PAGE_MAX: 0x8ff,

  PAGE_404: 0x404,

  // edit modes
  EDITMODE_NORMAL: 0,    // normal viewing
  EDITMODE_EDIT: 1,      // edit mode
  EDITMODE_ESCAPE: 2,    // expect next character to be either an edit.tf function or Escape again to exit.
  EDITMODE_INSERT: 3,    // The next character is ready to insert

  // state signals
  SIGNAL_PAGE_NOT_FOUND: -1,
  SIGNAL_INITIAL_LOAD: 2000,


  // config keys
  CONFIG: {
    TITLE: 'TITLE',
    HEADER_TITLE: 'HEADER_TITLE',

    BASE_DIR: 'BASE_DIR',
    BANNED_IP_ADDRESSES: 'BANNED_IP_ADDRESSES',

    TELETEXT_SERVER_URL: 'TELETEXT_SERVER_URL',
    TELETEXT_SERVER_PORT: 'TELETEXT_SERVER_PORT',

    TELETEXT_VIEWER_SERVE_HTTP: 'TELETEXT_VIEWER_SERVE_HTTP',
    TELETEXT_VIEWER_SERVE_HTTP_PORT: 'TELETEXT_VIEWER_SERVE_HTTP_PORT',

    TELETEXT_VIEWER_SERVE_HTTPS: 'TELETEXT_VIEWER_SERVE_HTTPS',
    TELETEXT_VIEWER_SERVE_HTTPS_PORT: 'TELETEXT_VIEWER_SERVE_HTTPS_PORT',
    TELETEXT_VIEWER_SERVE_HTTPS_KEY_PATH: 'TELETEXT_VIEWER_SERVE_HTTPS_KEY_PATH',
    TELETEXT_VIEWER_SERVE_HTTPS_CERT_PATH: 'TELETEXT_VIEWER_SERVE_HTTPS_CERT_PATH',

    TELETEXT_VIEWER_HTTPS_REJECT_UNAUTHORIZED: 'TELETEXT_VIEWER_HTTPS_REJECT_UNAUTHORIZED',

    CANVAS_WIDTH: 'CANVAS_WIDTH',
    CANVAS_HEIGHT: 'CANVAS_HEIGHT',

    FRONTEND_CONFIG_KEYS: 'FRONTEND_CONFIG_KEYS',
  },
};


if (typeof exports === 'object') {
  module.exports = CONST;
}