const CONST = {
  // page numbers
  PAGE_MIN: 0x100,
  PAGE_MAX: 0x8ff,

  PAGE_404: 0x404,

  // page files
  PAGE_EXT_TTI: '.tti',
  ENCODING_ASCII: 'ascii',

  // log levels
  LOG_LEVEL_VERBOSE: 3,
  LOG_LEVEL_INFO: 2,
  LOG_LEVEL_MANDATORY: 1,
  LOG_LEVEL_ERROR: 0,
  LOG_LEVEL_NONE: -1,

  // custom HTML attributes
  ATTR_DATA_SERVICE: 'data-service',
  ATTR_DATA_READY: 'data-ready',
  ATTR_DATA_SERVICE_EDITABLE: 'data-service-editable',
  ATTR_DATA_CONTROLS: 'data-controls',
  ATTR_DATA_DISPLAY: 'data-display',
  ATTR_DATA_SCALE: 'data-scale',
  ATTR_DATA_GRID: 'data-grid',
  ATTR_DATA_MENU_OPEN: 'data-menu-open',

  // edit modes
  EDITMODE_NORMAL: 0,    // normal viewing
  EDITMODE_EDIT: 1,      // edit mode
  EDITMODE_ESCAPE: 2,    // expect next character to be either an edit.tf function or Escape again to exit.
  EDITMODE_INSERT: 3,    // The next character is ready to insert

  // state signals
  SIGNAL_PAGE_NOT_FOUND: -1,
  SIGNAL_INITIAL_LOAD: 2000,

  // display modes
  DISPLAY_STANDARD: 'standard',
  DISPLAY_FITSCREEN: 'fitscreen',
  DISPLAY_FULLSCREEN: 'fullscreen',

  // control modes
  CONTROLS_STANDARD: 'standard',
  CONTROLS_ZAPPER: 'zapper',
  CONTROLS_MINIMAL: 'minimal',
  CONTROLS_BIGSCREEN: 'bigscreen',

  // services
  // (these ID's are also the name of the subdirectories of
  //  CONFIG.SERVICE_PAGES_DIR and CONFIG.SERVICE_PAGES_SERVE_DIR
  //  that contains the service's pages)
  SERVICE_TEEFAX: 'teefax',
  SERVICE_AMIGAROB: 'amigarob',
  SERVICE_ARTFAX: 'artfax',
  SERVICE_BBC1980: 'bbc1980',
  SERVICE_CHANNEL19: 'channel19',
  SERVICE_CHRISLUCA: 'chrisluca',
  SERVICE_DIGITISER: 'd2k',
  SERVICE_KINDIE: 'kindie',
  SERVICE_ARCHIVE: 'readback',
  SERVICE_TURNER: 'turner',
  SERVICE_WIKI: 'wtf',

  // config keys
  CONFIG: {
    IS_DEV: 'IS_DEV',

    LOG_LEVEL_TELETEXT_SERVER: 'LOG_LEVEL_TELETEXT_SERVER',
    LOG_LEVEL_TELETEXT_VIEWER: 'LOG_LEVEL_TELETEXT_VIEWER',

    SERVICE_PAGES_DIR: 'SERVICE_PAGES_DIR',
    SERVICE_PAGES_SERVE_DIR: 'SERVICE_PAGES_SERVE_DIR',

    PAGE_404_PATH: 'PAGE_404_PATH',

    LOGO_SVG_PATH: 'LOGO_SVG_PATH',
    ZAPPER_STANDARD_SVG_PATH: 'ZAPPER_STANDARD_SVG_PATH',
    ZAPPER_COMPACT_SVG_PATH: 'ZAPPER_COMPACT_SVG_PATH',

    SHOW_CONSOLE_LOGO: 'SHOW_CONSOLE_LOGO',
    CONSOLE_LOGO_CHAR_ARRAY: 'CONSOLE_LOGO_CHAR_ARRAY',

    TITLE: 'TITLE',
    HEADER_TITLE: 'HEADER_TITLE',

    BANNED_IP_ADDRESSES: 'BANNED_IP_ADDRESSES',

    TELETEXT_VIEWER_SERVE_HTTP: 'TELETEXT_VIEWER_SERVE_HTTP',
    TELETEXT_VIEWER_SERVE_HTTP_PORT: 'TELETEXT_VIEWER_SERVE_HTTP_PORT',

    TELETEXT_VIEWER_SERVE_HTTPS: 'TELETEXT_VIEWER_SERVE_HTTPS',
    TELETEXT_VIEWER_SERVE_HTTPS_PORT: 'TELETEXT_VIEWER_SERVE_HTTPS_PORT',
    TELETEXT_VIEWER_SERVE_HTTPS_KEY_PATH: 'TELETEXT_VIEWER_SERVE_HTTPS_KEY_PATH',
    TELETEXT_VIEWER_SERVE_HTTPS_CERT_PATH: 'TELETEXT_VIEWER_SERVE_HTTPS_CERT_PATH',

    TELETEXT_VIEWER_HTTPS_REJECT_UNAUTHORIZED: 'TELETEXT_VIEWER_HTTPS_REJECT_UNAUTHORIZED',

    SERVICES_AVAILABLE: 'SERVICES_AVAILABLE',

    DEFAULT_SERVICE: 'DEFAULT_SERVICE',
    DEFAULT_CONTROLS: 'DEFAULT_CONTROLS',
    DEFAULT_DISPLAY: 'DEFAULT_DISPLAY',
    DEFAULT_MENU_OPEN: 'DEFAULT_MENU_OPEN',
    DEFAULT_SCALE: 'DEFAULT_SCALE',

    OPEN_SERVICE_IN_NEW_WINDOW: 'OPEN_SERVICE_IN_NEW_WINDOW',

    // rendering
    NUM_COLUMNS: 'NUM_COLUMNS',
    NUM_ROWS: 'NUM_ROWS',

    CANVAS_WIDTH: 'CANVAS_WIDTH',
    CANVAS_HEIGHT: 'CANVAS_HEIGHT',
    CANVAS_PADDING_RIGHT_SINGLE_COLUMN: 'CANVAS_PADDING_RIGHT_SINGLE_COLUMN',


    FRONTEND_CONFIG_KEYS: 'FRONTEND_CONFIG_KEYS',
  },
};


if (typeof exports === 'object') {
  module.exports = CONST;
}